name: odpalgadke
description: "OdpalGadkę to inteligentny trener rozmów, który uczy mówić pewnie i swobodnie w każdej sytuacji"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  responsive_sizer: ^3.3.1
  flutter_bloc: ^9.1.1
  go_router: ^17.0.0
  get_it: ^9.0.5
  dio: ^5.9.0
  google_fonts: ^6.3.2
  another_flushbar: ^1.12.32
  either_dart: ^1.0.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  shadcn_flutter: ^0.0.47
  intl: ^0.20.2
  pretty_dio_logger: ^1.4.0
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  equatable: ^2.0.7
  bloc: ^9.1.0
  web_socket_channel: ^3.0.3
  just_audio: ^0.10.5
  path_provider: ^2.1.5
  record: ^6.1.2
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.2
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:

  uses-material-design: true